version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rada.info
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  default:
    name: rada
    driver: bridge